services:
  db:
    restart: unless-stopped
    image: mariadb:10.11
    container_name: radius-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  radius:
    restart: unless-stopped
    build:
      context: ./radius
    container_name: radius-server
    command: [ "freeradius", "-X" ]
    env_file:
      - .env
    environment:
      # Default: bridge networking — connects via Docker service hostname
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      # Debug mode enabling
      RADIUS_DEBUG: "${RADIUS_DEBUG:-no}"
    volumes:
      - ./backend/dictionaries:/etc/raddb/custom_dictionaries
      - ./radius/sql:/etc/raddb/mods-available/sql
      - ./radius/clients.conf:/etc/raddb/clients.conf
      - ./radius/default.conf:/etc/freeradius/sites-enabled/default
      - ./radius/certs:/etc/freeradius/certs
    depends_on:
      db:
        condition: service_healthy

  backend:
    restart: unless-stopped
    build:
      context: ./backend
    container_name: radius-backend
    volumes:
      - ./backend:/app
      - ./radius/certs:/etc/freeradius/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp:ro
    env_file:
      - .env
    environment:
      # Using hostname 'db' to connect to the database service
      DATABASE_URL: mysql+aiomysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    container_name: radius-frontend
    ports:
      - "3009:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs

volumes:
  db_data:
